#!/bin/bash

rm -fR Auditool
meteor-kitchen http://www.meteorkitchen.com/api/getapp/json/Tqq4JcxsuGEBZrben AuditTool

cp /home/mtt/AuditTool/files/hacking/fileinput.js home/mtt/AuditTool/AuditTool/client/styles/framework/bootstrap3-plugins/bootstrap-fileinput

cd AuditTool

meteor
